//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_tanphunongEntities : DbContext
    {
        public db_tanphunongEntities()
            : base("name=db_tanphunongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_BaiViet> tb_BaiViet { get; set; }
        public virtual DbSet<tb_BaiVietTrans> tb_BaiVietTrans { get; set; }
        public virtual DbSet<tb_DoiNguQL_Trans> tb_DoiNguQL_Trans { get; set; }
        public virtual DbSet<tb_DoiNguQuanLy> tb_DoiNguQuanLy { get; set; }
        public virtual DbSet<tb_LoaiSP> tb_LoaiSP { get; set; }
        public virtual DbSet<tb_LoaiSPTrans> tb_LoaiSPTrans { get; set; }
        public virtual DbSet<tb_NguoiDung> tb_NguoiDung { get; set; }
        public virtual DbSet<tb_NhatKy> tb_NhatKy { get; set; }
        public virtual DbSet<tb_PhanHoi> tb_PhanHoi { get; set; }
        public virtual DbSet<tb_SanPham> tb_SanPham { get; set; }
        public virtual DbSet<tb_SanPhamTrans> tb_SanPhamTrans { get; set; }
        public virtual DbSet<tb_TuyChon> tb_TuyChon { get; set; }
        public virtual DbSet<tb_DoiTac> tb_DoiTac { get; set; }
    }
}
