//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Album
    {
        public tb_Album()
        {
            this.tb_Photos = new HashSet<tb_Photos>();
        }
    
        public int MaAlbum { get; set; }
        public string TenAlbum { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<tb_Photos> tb_Photos { get; set; }
    }
}
