//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_BaiViet
    {
        public int MaBV { get; set; }
        [Display(Name = "Tiêu đề")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Tiêu đề không được trống")]
        public string TieuDe { get; set; }
        [Display(Name = "Tóm tắt")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Tóm tắt không được trống")]
        public string TomTat { get; set; }
        [Display(Name = "Nội dung")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nội dung không được trống")]
        public string NoiDung { get; set; }
        public Nullable<int> LoaiBaiViet { get; set; }
        [Display(Name = "Ngày viết")]
        public Nullable<System.DateTime> NgayViet { get; set; }
        [Display(Name = "Hình ảnh")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Hình ảnh không được trống")]
        public string HinhAnh { get; set; }
        [Display(Name = "Người viết")]
        public string NguoiViet { get; set; }
    
        public virtual tb_NguoiDung tb_NguoiDung { get; set; }
    }
}
