//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BaiVietTrans
    {
        public int MaBV { get; set; }
        public string TieuDeTrans { get; set; }
        public string TomTatTrans { get; set; }
        public string NoiDungTrans { get; set; }
        public string NgonNgu { get; set; }
    
        public virtual tb_BaiViet tb_BaiViet { get; set; }
    }
}
