//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class tb_DoiTac
    {
        public int MaDT { get; set; }
        [Display(Name = "Tên đối tác")]
        [Required(ErrorMessage = "Tên đối tác không được để trống", AllowEmptyStrings = false)]
        public string TenDT { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email không được để trống", AllowEmptyStrings = false)]
        public string Email { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Địa chỉ đối tác không được để trống", AllowEmptyStrings = false)]
        public string DiaChi { get; set; }
        [Display(Name = "Giới thiệu")]
        public string ChiTiet { get; set; }
        [Display(Name = "Trang web")]
        public string WebsiteDT { get; set; }
    }
}
