//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LoaiSPTrans
    {
        public int MaLoaiSP { get; set; }
        public string TenLoaiSPTrans { get; set; }
        public string MoTaTrans { get; set; }
        public string NgonNgu { get; set; }
    
        public virtual tb_LoaiSP tb_LoaiSP { get; set; }
    }
}
