//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NguoiDung
    {
        public tb_NguoiDung()
        {
            this.tb_BaiViet = new HashSet<tb_BaiViet>();
            this.tb_LoaiSP = new HashSet<tb_LoaiSP>();
            this.tb_SanPham = new HashSet<tb_SanPham>();
        }
    
        [Display(Name = "Tên đăng nhập")]
        [Required(AllowEmptyStrings = false,ErrorMessage = "Tên đăng nhập không thể để trống")]
        public string TenDangNhap { get; set; }
        [Display(Name = "Mật khẩu")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Mật khẩu không thể để trống")]
        public string MatKhau { get; set; }
        [Display(Name = "Trạng thái")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Trạng thái không thể để trống")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name = "Quyền")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phải xét quyền người dùng")]
        public string LoaiND { get; set; }
        [Display(Name = "Đăng nhập cuối")]
        public Nullable<System.DateTime> ThoiGianDNCuoi { get; set; }
    
        public virtual ICollection<tb_BaiViet> tb_BaiViet { get; set; }
        public virtual ICollection<tb_LoaiSP> tb_LoaiSP { get; set; }
        public virtual ICollection<tb_SanPham> tb_SanPham { get; set; }
    }
}
