//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhatKy
    {
        public int MaNK { get; set; }
        public string NguoiDung { get; set; }
        public string DoiTuong { get; set; }
        public string ThaoTac { get; set; }
        public Nullable<int> MaDoiTuong { get; set; }
    }
}
