//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Photos
    {
        public int MaPhoTo { get; set; }
        public string Link { get; set; }
        public Nullable<int> MaAlbum { get; set; }
        public string MoTa { get; set; }
    
        public virtual tb_Album tb_Album { get; set; }
    }
}
