//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhanHoi
    {
        public int MaPH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
    }
}
