//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SanPhamTrans
    {
        public int MaSP { get; set; }
        public string TenSanPhamTrans { get; set; }
        public string UuDienTrans { get; set; }
        public string DacDiemTrans { get; set; }
        public string ThanhPhanChinhTrans { get; set; }
        public string LuuYTrans { get; set; }
        public string QuyCachDongGoiTrans { get; set; }
        public string CachDungTrans { get; set; }
        public string NgonNgu { get; set; }
    
        public virtual tb_SanPham tb_SanPham { get; set; }
    }
}
