//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Web.Mvc;

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_SanPham
    {
        public int MaSP { get; set; }
        [Display(Name = "Tên SP")]
        public string TenSanPham { get; set; }
        [Display(Name = "Ưu điểm")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ưu điểm không được để trống")]
        public string UuDiem { get; set; }
        [Display(Name = "Đặc điểm")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Đặc điểm không được để trống")]
        [AllowHtml]
        public string DacDiem { get; set; }
        [Display(Name = "Thành phần chính")]
        [AllowHtml]
        public string ThanhPhanChinh { get; set; }
        [Display(Name = "Lưu ý")]
        [AllowHtml]
        public string LuuY { get; set; }
        [Display(Name = "Quy cách đóng gói")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quy cách đóng gói không được để trống")]
        public string QuyCachDongGoi { get; set; }
        [Display(Name = "Xuất xứ")]
        public string XuatXu { get; set; }
        [Display(Name = "Cách dùng")]
        [AllowHtml]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Cách dùng không được để trống")]
        public string CachDung { get; set; }
        [Display(Name = "Giá tham khảo")]
        public Nullable<decimal> GiaThanh { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name = "Thuộc loại")]
        public int MaLoai { get; set; }
        [Display(Name = "Hình ảnh")]
        public string HinhAnh { get; set; }
        [Display(Name = "Người Thêm")]
        public string NguoiThem { get; set; }
    
        public virtual tb_LoaiSP tb_LoaiSP { get; set; }
        public virtual tb_NguoiDung tb_NguoiDung { get; set; }
    }
}
