//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SanPham
    {
        public int MaSP { get; set; }
        public string TenSanPham { get; set; }
        public string UuDiem { get; set; }
        public string DacDiem { get; set; }
        public string ThanhPhanChinh { get; set; }
        public string LuuY { get; set; }
        public string QuyCachDongGoi { get; set; }
        public string XuatXu { get; set; }
        public string CachDung { get; set; }
        public Nullable<decimal> GiaThanh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int MaLoai { get; set; }
    
        public virtual tb_LoaiSP tb_LoaiSP { get; set; }
    }
}
