//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DACN_TanPhuNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TuyChon
    {
        [Display(Name = "Mã tùy chọn")]
        public int MaTuyChon { get; set; }
        [Display(Name = "Tên tùy chọn")]
        public string TenTuyChon { get; set; }
        [AllowHtml]
        [Display(Name = "Nội dung tùy chọn")]
        public string NoiDungTuyChon { get; set; }
    }
}
